---
## top-most configuration
root: true

parser: babel-eslint

plugins:
  - babel

env:
  es6: true
  node: true
  browser: true
  worker: true
  serviceworker: true

parserOptions:
  ecmaVersion: 7
  soureType: module

rules:
  ## babel
  babel/generator-star-spacing: 1
  babel/new-cap: 1
  babel/array-bracket-spacing: 1
  babel/object-curly-spacing: 1
  babel/object-shorthand: 1
  babel/arrow-parens: 1
  babel/no-await-in-loop: 0
  babel/flow-object-type: 0

  ## possible errors
  comma-dangle: 1
  no-cond-assign: 1
  no-console: 1
  no-constant-condition: 0 # loose rule: 화살표 함수는 항상 괄호를 쓰므로 문제가 되지 않으며 `while(true)`를 위해 비활성화
  no-control-regex: 1
  no-debugger: 1
  no-dupe-args: 2
  no-dupe-keys: 1
  no-duplicate-case: 1
  no-empty:
    - 1
    # - allowEmptyCatch: true
  no-empty-character-class: 1
  no-ex-assign: 2
  no-extra-boolean-cast: 1
  no-extra-parens: 1
  no-extra-semi: 1
  no-func-assign: 2
  no-inner-declarations: 1
  no-invalid-regexp: 2
  no-irregular-whitespace: 2
  no-negated-in-lhs: 1
  no-obj-calls: 2
  no-regex-spaces: 1
  no-sparse-arrays: 0
  no-unexpected-multiline: 2
  no-unreachable: 1
  use-isnan: 1 # Number.isNaN
  valid-jsdoc: 0
  valid-typeof: 2

  ## best practices
  accessor-pairs: 0
  array-callback-return: 1
  block-scoped-var: 0 # unused
  complexity: 0
  consistent-return: 0 # loose rule: `null` 값을 반환할 때도 있다
  curly: 1
  default-case: 1
  dot-location:
    - 1
    - property
  dot-notation: 0
  eqeqeq: 0
  guard-for-in: 0
  no-alert: 0
  no-caller: 2
  no-case-declarations: 1
  no-div-regex: 0
  no-else-return: 1
  no-empty-function: 1
  no-empty-pattern: 2
  no-eq-null: 1
  no-eval: 1
  no-extend-native: 1
  no-extra-bind: 1
  no-extra-label: 1
  no-fallthrough: 1
  no-floating-decimal: 1
  no-implicit-coercion: 0
  no-implicit-globals: 0 # unused
  no-implied-eval: 1
  no-invalid-this: 1
  no-iterator: 2
  no-labels: 1
  no-lone-blocks: 1
  no-loop-func: 0
  no-magic-numbers: 0 # ?
  no-multi-spaces: 1
  no-multi-str: 1
  no-native-reassign: 2
  no-new: 0
  no-new-func: 2
  no-new-wrappers: 1
  no-octal: 2
  no-octal-escape: 2
  no-param-reassign: 0 # loose rule
  no-proto: 2
  no-redeclare: 2
  no-return-assign: 0
  no-script-url: 0
  no-self-assign: 1
  no-self-compare: 1
  no-sequences: 0
  no-throw-literal: 2
  no-unmodified-loop-condition: 1
  no-unused-expressions: 1
  no-unused-labels: 2
  no-useless-call: 1
  no-useless-concat: 1
  no-useless-escape: 1
  no-void: 2
  no-warning-comments: 0
  no-with: 2
  radix: 0
  vars-on-top: 0
  wrap-iife:
    - 1
    - inside
  yoda: 1

  ## strict mode
  strict: 0

  ## variables
  init-declarations: 0
  no-catch-shadow: 0
  no-delete-var: 2
  no-label-var: 1
  no-restricted-globals: 0
  no-shadow: 0
  no-shadow-restricted-names: 1
  no-undef: 2
  no-undef-init: 1
  no-undefined: 1
  no-unused-vars: 1
  no-use-before-define: 0 # loose rule: 메서드 내의 화살표 함수 표현식은 서로 참조해서 쓸 수 있다

  ## node.js and commonjs
  callback-return: 0
  # callback-return:
  #   - 1
  #   - - resolve
  #     - reject
  #     - callback
  #     - next
  global-require: 1
  handle-callback-err: 0
  no-mixed-requires: 0
  no-new-require: 0
  no-path-concat: 1
  no-process-env: 0
  no-process-exit: 0
  no-restricted-modules: 0
  no-sync: 0

  ## stylistic issues
  # array-bracket-spacing: 1
  block-spacing: 1
  brace-style:
    - 1
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - 1
    - properties: never
  comma-spacing: 1
  comma-style:
    - 1
    - last
  computed-property-spacing: 1
  consistent-this: 0
  eol-last: 1
  func-names: 0
  func-style: 0
  id-blacklist: 0
  id-length: 0
  id-match: 0
  indent:
    - 1
    - 2
    - SwitchCase: 1
  jsx-quotes: 1
  key-spacing: 0
  keyword-spacing: 1
  linebreak-style: 1
  lines-around-comment: 0
  max-depth: 0
  max-len: 0
  max-nested-callbacks: 0
  max-params: 0
  max-statements: 0
  max-statements-per-line: 0
  # new-cap: 1
  new-parens: 1
  newline-after-var: 0
  newline-before-return: 0
  newline-per-chained-call: 0 # loose rule
  no-array-constructor: 1
  no-bitwise: 0
  no-continue: 0
  no-inline-comments: 0
  no-lonely-if: 1
  no-mixed-spaces-and-tabs: 1
  no-multiple-empty-lines:
    - 1
    - max: 2
  no-negated-condition: 1
  no-nested-ternary: 0
  no-new-object: 1
  no-plusplus: 0
  no-restricted-syntax:
    - 2
    - WithStatement
  no-spaced-func: 1
  no-ternary: 0
  no-trailing-spaces:
    - 1
    - skipBlankLines: true
  no-underscore-dangle: 0
  no-unneeded-ternary:
    - 1
    - defaultAssignment: false
  no-whitespace-before-property: 1
  # object-curly-spacing: 1
  one-var: 0
  one-var-declaration-per-line: 0
  operator-assignment:
    - 1
    - always
  operator-linebreak: 1
  padded-blocks: 0
  quote-props:
    - 1
    - as-needed
  quotes:
    - 1
    - single
  require-jsdoc: 0
  semi: 2
  semi-spacing: 1
  sort-imports: 0 # ambiguous rule
  sort-vars: 0
  space-before-blocks: 1
  space-before-function-paren:
    - 1
    - never
  space-in-parens: 1
  space-infix-ops: 1
  space-unary-ops: 1
  spaced-comment: 0
  wrap-regex: 0

  ## ecmascript 6
  arrow-body-style: 0
  # arrow-parens: 1
  arrow-spacing: 1
  constructor-super: 2
  # generator-star-spacing: 1
  no-class-assign: 2
  no-confusing-arrow: 0
  no-const-assign: 2
  no-dupe-class-members: 2
  no-duplicate-imports:
    - 1
    - includeExports: true
  no-new-symbol: 2
  no-restricted-imports: 0
  no-this-before-super: 2
  no-useless-constructor: 1
  no-var: 2
  # object-shorthand: 1
  prefer-arrow-callback: 1
  prefer-const: 0
  prefer-reflect: 1
  prefer-rest-params: 1
  prefer-spread: 1
  prefer-template: 0 # loose rule: '' + n 과 같이 타입 캐스팅을 할 수도 있다
  require-yield: 1
  template-curly-spacing: 1
  yield-star-spacing: 1
